"use client";
import {useMemo,useState} from "react";
import {Search,ArrowUpRight,Calculator,ShieldCheck,ChevronDown} from "lucide-react";
import {LineChart,Line,XAxis,YAxis,Tooltip,ResponsiveContainer,CartesianGrid} from "recharts";
import {funds,categories,Fund} from "@/lib/funds";
import {yearlyProjection,money} from "@/lib/calculations";
const periods=[["oneY","1Y"],["threeY","3Y p.a."],["fiveY","5Y p.a."],["tenY","10Y p.a."],["sinceInception","Since inception"]] as const;
export default function Home(){
 const [tab,setTab]=useState<"explore"|"compare"|"simulator">("explore"),[query,setQuery]=useState(""),[category,setCategory]=useState("All");
 const [selected,setSelected]=useState<string[]>(["portfolio-100","global-technology","global-equity"]);
 const filtered=useMemo(()=>funds.filter(f=>(category==="All"||f.category===category)&&f.name.toLowerCase().includes(query.toLowerCase())),[query,category]);
 const toggle=(id:string)=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):s.length<5?[...s,id]:s);
 return <main><header className="topbar"><div className="brand"><div className="brandMark">FI</div><div><strong>Fund Intel</strong><span>AIA Fund Intelligence</span></div></div><div className="dataStatus"><span className="dot"/> Research workspace <span className="pill">No login</span></div></header>
 <section className="hero"><div><div className="eyebrow">INDEPENDENT FUND RESEARCH</div><h1>Understand the fund.<br/><em>Model the future.</em></h1><p>Explore AIA ILP funds, compare historical performance, and model potential investment outcomes in one focused workspace.</p><div className="heroActions"><button className="primary" onClick={()=>setTab("explore")}>Explore funds <ArrowUpRight size={17}/></button><button className="secondary" onClick={()=>setTab("simulator")}><Calculator size={17}/> Investment simulator</button></div></div><div className="heroCard"><div className="miniLabel">FUNDS IN WORKSPACE</div><div className="heroNumber">{funds.length}</div><div className="miniLine">AIA-focused fund catalogue</div><div className="miniGrid"><div><b>5</b><span>comparison slots</span></div><div><b>30 yrs</b><span>projection horizon</span></div></div></div></section>
 <nav className="tabs">{[["explore","Fund Explorer"],["compare","Compare Funds"],["simulator","Investment Simulator"]].map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id as typeof tab)}>{label}</button>)}</nav>
 {tab==="explore"&&<Explorer filtered={filtered} query={query} setQuery={setQuery} category={category} setCategory={setCategory} onToggle={toggle} selected={selected}/>}
 {tab==="compare"&&<Compare selected={selected.map(id=>funds.find(f=>f.id===id)).filter(Boolean) as Fund[]}/>}
 {tab==="simulator"&&<Simulator selected={selected} onSelect={setSelected}/>}
 <footer><ShieldCheck size={15}/> Data shown in this prototype is illustrative and must be replaced or validated against authorised AIA fund data before client use. Past performance is not indicative of future performance.</footer></main>;
}
function Explorer({filtered,query,setQuery,category,setCategory,onToggle,selected}:{filtered:Fund[];query:string;setQuery:(x:string)=>void;category:string;setCategory:(x:string)=>void;onToggle:(x:string)=>void;selected:string[]}){
 return <section className="content"><div className="sectionHead"><div><div className="eyebrow">AIA FUND CATALOGUE</div><h2>Find a fund</h2></div><div className="controls"><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search funds..."/></div><div className="selectWrap"><select value={category} onChange={e=>setCategory(e.target.value)}><option>All</option>{categories.map(c=><option key={c}>{c}</option>)}</select><ChevronDown size={15}/></div></div></div><div className="fundGrid">{filtered.map(f=><FundCard key={f.id} fund={f} selected={selected.includes(f.id)} onToggle={onToggle}/>)}</div></section>;
}
function FundCard({fund,selected,onToggle}:{fund:Fund;selected:boolean;onToggle:(x:string)=>void}){
 return <article className={selected?"fundCard selected":"fundCard"}><div className="cardTop"><span className="tag">{fund.category}</span><button className="compareBtn" onClick={()=>onToggle(fund.id)}>{selected?"Selected":"+ Compare"}</button></div><h3>{fund.name}</h3><p>{fund.description}</p><div className="metricRow"><div><span>1Y</span><strong>{fund.returns.oneY.toFixed(1)}%</strong></div><div><span>5Y p.a.</span><strong>{fund.returns.fiveY.toFixed(1)}%</strong></div><div><span>Risk</span><strong>{"●".repeat(fund.risk)}<i>{"●".repeat(5-fund.risk)}</i></strong></div></div><div className="cardBottom"><span>{fund.currency} · Fee {fund.fee.toFixed(2)}%</span><span>Since {fund.inception}</span></div></article>;
}
function Compare({selected}:{selected:Fund[]}){
 const rows=periods.map(([key,label])=>({label,values:selected.map(f=>f.returns[key])}));
 return <section className="content"><div className="sectionHead"><div><div className="eyebrow">SIDE-BY-SIDE ANALYSIS</div><h2>Compare funds</h2><p className="muted">Use the Fund Explorer to select up to five funds.</p></div></div><div className="compareTable"><div className="tableHeader"><span>Performance</span>{selected.map(f=><span key={f.id}>{f.name.replace("AIA ","")}</span>)}</div>{rows.map(r=><div className="tableRow" key={r.label}><span>{r.label}</span>{r.values.map((v,i)=><strong key={i}>{v.toFixed(2)}%</strong>)}</div>)}<div className="tableRow"><span>Annual fee</span>{selected.map(f=><strong key={f.id}>{f.fee.toFixed(2)}%</strong>)}</div></div><div className="compareChart"><div className="chartTitle">Relative performance snapshot <small>Illustrative indexed view</small></div><ResponsiveContainer width="100%" height={300}><LineChart data={Array.from({length:6},(_,i)=>({year:String(2021+i),...Object.fromEntries(selected.map(f=>[f.id,100*Math.pow(1+f.returns.fiveY/100,i/5)]))}))}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="year"/><YAxis/><Tooltip/>{selected.map(f=><Line key={f.id} type="monotone" dataKey={f.id} name={f.name.replace("AIA ","")} strokeWidth={2.5} dot={false}/>)}</LineChart></ResponsiveContainer></div></section>;
}
function Simulator({selected,onSelect}:{selected:string[];onSelect:(x:string[])=>void}){
 const [initial,setInitial]=useState(500000),[annual,setAnnual]=useState(24000),[years,setYears]=useState(20),[mode,setMode]=useState<"auto"|"manual">("auto"),[manual,setManual]=useState(8);
 const primary=funds.find(f=>f.id===selected[0])??funds[0],auto=primary.returns.fiveY,rate=mode==="auto"?auto:manual,projection=yearlyProjection(initial,rate,years,annual),end=projection.at(-1)?.end??initial,gain=end-initial-annual*years;
 return <section className="content"><div className="sectionHead"><div><div className="eyebrow">WHAT-IF MODELLING</div><h2>Investment simulator</h2><p className="muted">Model a lump sum and recurring contributions with either a fund-linked or manual assumption.</p></div></div><div className="simGrid"><div className="panel inputs"><label>Initial investment<input type="number" value={initial} onChange={e=>setInitial(+e.target.value)}/></label><label>Annual contribution<input type="number" value={annual} onChange={e=>setAnnual(+e.target.value)}/></label><label>Investment period <b>{years} years</b><input type="range" min="1" max="30" value={years} onChange={e=>setYears(+e.target.value)}/></label><label>Fund for automatic assumption<select value={primary.id} onChange={e=>onSelect([e.target.value,...selected.filter(x=>x!==e.target.value)])}>{funds.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><div className="mode"><button className={mode==="auto"?"modeActive":""} onClick={()=>setMode("auto")}>Automatic</button><button className={mode==="manual"?"modeActive":""} onClick={()=>setMode("manual")}>Manual</button></div>{mode==="manual"?<label>Manual expected return <input type="number" step="0.1" value={manual} onChange={e=>setManual(+e.target.value)}/></label>:<div className="autoBox"><span>Automatic expected return</span><strong>{auto.toFixed(2)}%</strong><small>Uses the selected fund's 5Y p.a. figure in this prototype.</small></div>}</div><div className="panel result"><div className="resultTop"><div><span>Potential value after {years} years</span><strong>{money(end)}</strong></div><div className="rateBadge">{rate.toFixed(2)}% assumption</div></div><div className="statGrid"><div><span>Total contributions</span><b>{money(initial+annual*years)}</b></div><div><span>Estimated growth</span><b>{money(gain)}</b></div><div><span>Selected fund</span><b>{primary.name.replace("AIA ","")}</b></div></div><ResponsiveContainer width="100%" height={330}><LineChart data={projection.map(r=>({year:r.year,value:Math.round(r.end)}))}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="year"/><YAxis/><Tooltip/><Line type="monotone" dataKey="value" strokeWidth={3} dot={false}/></LineChart></ResponsiveContainer><div className="formula">Projection uses annual compounding and end-of-year contributions. This is a mathematical illustration, not a forecast or guarantee.</div></div></div></section>;
}