export type Fund={id:string;name:string;category:string;risk:number;currency:string;fee:number;inception:number;returns:{oneY:number;threeY:number;fiveY:number;tenY:number;sinceInception:number};description:string};
export const funds:Fund[]=[
{id:"portfolio-100",name:"AIA Portfolio 100 Fund",category:"Equity / Growth",risk:5,currency:"SGD",fee:1.5,inception:2000,returns:{oneY:18.71,threeY:19.18,fiveY:13.28,tenY:9.02,sinceInception:4.1},description:"Growth-oriented diversified portfolio designed for long-term capital appreciation."},
{id:"global-technology",name:"AIA Global Technology Fund",category:"Global Equity / Technology",risk:5,currency:"USD",fee:1.5,inception:2000,returns:{oneY:22.4,threeY:18.1,fiveY:16.2,tenY:13.4,sinceInception:8.6},description:"Concentrated global technology exposure with a higher-growth, higher-volatility profile."},
{id:"global-equity",name:"AIA Global Equity Fund",category:"Global Equity",risk:4,currency:"USD",fee:1.5,inception:2000,returns:{oneY:15.2,threeY:12.8,fiveY:11.3,tenY:8.7,sinceInception:5.9},description:"Diversified global equity exposure across developed and emerging markets."},
{id:"emerging-equity",name:"AIA Emerging Market Equity Fund",category:"Emerging Market Equity",risk:5,currency:"USD",fee:1.5,inception:2000,returns:{oneY:11.8,threeY:8.6,fiveY:7.9,tenY:6.2,sinceInception:4.8},description:"Equity exposure focused on emerging economies and their long-term growth potential."},
{id:"emerging-balanced",name:"AIA Emerging Market Balanced Fund",category:"Balanced",risk:4,currency:"USD",fee:1.35,inception:2000,returns:{oneY:9.4,threeY:7.2,fiveY:6.8,tenY:5.9,sinceInception:4.4},description:"Balanced exposure to emerging-market equities and fixed income."},
{id:"adventurous-index",name:"AIA Adventurous Index Fund",category:"Global Equity / Index",risk:5,currency:"USD",fee:1.25,inception:2014,returns:{oneY:17.6,threeY:13.9,fiveY:12.7,tenY:9.8,sinceInception:8.1},description:"Aggressive index-oriented allocation intended for investors with a long investment horizon."},
{id:"balanced",name:"AIA Balanced Fund",category:"Multi-Asset",risk:3,currency:"SGD",fee:1.25,inception:2000,returns:{oneY:8.1,threeY:6.4,fiveY:6.1,tenY:5.2,sinceInception:4.2},description:"Multi-asset approach seeking a balance between capital growth and portfolio stability."},
{id:"conservative",name:"AIA Conservative Fund",category:"Fixed Income / Multi-Asset",risk:2,currency:"SGD",fee:1,inception:2000,returns:{oneY:4.8,threeY:3.9,fiveY:3.7,tenY:3.2,sinceInception:3},description:"Lower-risk allocation focused on capital preservation and income."}
];
export const categories=[...new Set(funds.map(f=>f.category))];